version: "3"

services:
  db:
    build: ./docker/db
    ports:
      -  "5432:5432"
    environment:
      - POSTGRES_DB=solitaacademy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.dev
    volumes:
      -  ./src:/app/src
    ports:
      -  "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=solitaacademy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db